---
- name: copy app.py to webservers
  hosts: webserver
  become: yes

  tasks:
    - name: Ensure /home/ec2-user/app directory exists
      file:
        path: /home/ec2-user/app
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0755'

    - name: Copy app.py to the web server
      copy:
        src: app.py
        dest: /home/ec2-user/app/app.py
        owner: ec2-user
        group: ec2-user
        mode: '0644'

    - name: Set environment variables for app
      copy:
        dest: /etc/environment
        content: |
            DB_HOST="10.0.2.63"
            DB_NAME="mydb"
            DB_USER="myuser"
            DB_PASSWORD="mypassword"
        mode: '0644'


    - name: Run Flask app with environment variables
      shell: |
        nohup env DB_HOST=10.0.2.63 DB_NAME=mydb DB_USER=myuser DB_PASSWORD=mypassword \
        python3 /home/ec2-user/app/app.py > /home/ec2-user/app/output.log 2>&1 &
      args:
        chdir: /home/ec2-user/app

