---
- name: Install and start Docker on Amazon Linux 2023
  hosts: webserver
  become: yes

  tasks:
    - name: Install Docker from default repo
      ansible.builtin.dnf:
        name: docker
        state: latest

    - name: Start and enable Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Verify Docker is running
      ansible.builtin.command: systemctl is-active docker
      register: docker_status
      changed_when: false
      failed_when: "'active' not in docker_status.stdout"
