---
- name: Install and start Python on Amazon Linux 2023
  hosts: webserver
  become: yes

  tasks:
    - name: Install Python from default repo
      ansible.builtin.dnf:
        name: python3
        state: latest

    - name: Pip installation
      ansible.builtin.dnf:
        name: python3-pip
        state: present
       

    - name: Verify python version
      ansible.builtin.command: 
        cmd: python3 --version
        register: python_version
        changed_when: false
        

    - name: Show python version
      ansible.builtin.debug:
       var: python_version.stdout
    
    - name: Install Flask
      ansible.builtin.command:
        cmd: pip3 install Flask
        register: flask_install
        state: present
    
    - name: Verify Flask installation
      command: python3 -c "import flask; print(flask.version)"
      register: flask_version
      
    - name: install psycopg2
      ansible.builtin.command:
        cmd: pip3 install psycopg2
        register: psycopg2_install
        state: present
     